version: "3"
services: 
  app_sgraph:
    container_name: graphql-server-typeorm  
    restart: always
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    ports: 
      - "5000:5001"
    volumes:
      - .:/app
    networks:
      - sgraph-network 

  postgres:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: server-graphql_dev
    networks:
      - sgraph-network 

  # pgadmin:
  #   image: dpage/pgadmin4
  #   links:
  #     - postgres
  #   restart: always
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 5010:80
  #   ## you can change pgAdmin default username/password with below environment variables
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   networks:
  #     - sgraph-network 


networks:
  sgraph-network:
    driver: bridge